/**
 * WeLearn backend API
 * C1 version of the WeLearn Backend API
 *
 * OpenAPI spec version: 1.0
 * Contact: ivelin.dimitrov9@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScheduleDto { 
    dayOfWeek: string;
    disciplineId: string;
    endDate: Date;
    endHour: Date;
    groupId: string;
    id?: string;
    resourceIds?: Array<string>;
    startDate: Date;
    startHour: Date;
}
