/**
 * WeLearn backend API
 * C1 version of the WeLearn Backend API
 *
 * OpenAPI spec version: 1.0
 * Contact: ivelin.dimitrov9@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EvaluationMarkDto } from './evaluationMarkDto';
import { RoleDto } from './roleDto';


export interface UserDto { 
    address?: string;
    assistedDisciplineIds?: Array<string>;
    birthdate?: Date;
    blackListedEventIds?: Array<string>;
    deleted?: number;
    email?: string;
    evaluationMarks?: Array<EvaluationMarkDto>;
    firstName?: string;
    groupId?: string;
    lastName?: string;
    loggedIn?: number;
    middleName?: string;
    password?: string;
    phoneNumber?: string;
    role?: RoleDto;
    taughtDisciplineIds?: Array<string>;
    userId?: string;
    username?: string;
}
